spring:
  datasource:
    url: ${db_url}
    username: ${db_username}
    password: ${db_password}
  jpa:
    properties:
      dialect:
        hibernate: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  flyway:
    enabled: true
